# Generated by Django 4.2.20 on 2025-05-07 07:49

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(help_text='e.g., City, Region, Country', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_types', models.JSONField(blank=True, default=list, help_text="List of services offered, e.g., ['Term Loan', 'Trade Finance']")),
                ('geos_served', models.JSONField(blank=True, default=list, help_text="List of geographical areas served, e.g., ['Metro Manila', 'Cebu City']")),
                ('subscription_tier', models.CharField(choices=[('NONE', 'None'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium')], default='NONE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(help_text='e.g., City, Region, Country', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.CharField(help_text='e.g., Manufacturing, Retail, Technology', max_length=100)),
                ('rating_report_url', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Secure URL to the rating report (encrypted at rest)', null=True, verbose_name='Rating Report URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
